#!/usr/bin/env bash
set -euo pipefail

mkdir -p dist

bun build ./index.ts --compile --target=bun-linux-x64 --outfile=dist/boxfiles-linux-x64
bun build ./index.ts --compile --target=bun-linux-arm64 --outfile=dist/boxfiles-linux-arm64
bun build ./index.ts --compile --target=bun-darwin-x64 --outfile=dist/boxfiles-darwin-x64
bun build ./index.ts --compile --target=bun-darwin-arm64 --outfile=dist/boxfiles-darwin-arm64
bun build ./index.ts --compile --target=bun-windows-x64 --outfile=dist/boxfiles-windows-x64.exe
